#!/bin/bash

FULLFILENAME=$1
properextension="deb_bundle"


if [ -z "$FULLFILENAME" ]
then
  echo "Please enter a valide filename with exntesion .deb_bundel"
  exit 1;
else
  echo "          Welcome to Bundel"
fi

fullpath=$1
filename="${fullpath##*/}"                      # Strip longest match of */ from start
dir="${fullpath:0:${#fullpath} - ${#filename}}" # Substring from 0 thru pos of filename
base="${filename%.[^.]*}"                       # Strip shortest match of . plus at least one non-dot char from end
ext="${filename:${#base} + 1}"                  # Substring from len of base thru end
if [[ -z "$base" && -n "$ext" ]]; then          # If we have an extension and no base, it's really the base
   base=".$ext"
   ext=""
fi

#echo -e "$fullpath:\n\tdir  = \"$dir\"\n\tbase = \"$base\"\n\text  = \"$ext\""


## check if it has .deb_bundel extension 

if [ "$ext" = "$properextension" ]
then
echo "";
else
echo This is not a valid file
exit 1
fi



### extract the file name of bundel  ######
APP_NAME=$base
echo " ===========     Now installing $APP_NAME ============="
TMPDIR=/tmp/BUN/$APP_NAME
mkdir -p $TMPDIR
rm -rf  $TMPDIR/*
tar -xvf $FULLFILENAME -C $TMPDIR



### Installing the all the deb packages

sudo dpkg -i $TMPDIR/*.deb

### Delete Whole tmp Directory

rm -rf $TMPDIR

exit 0
